const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const get=x=>fs.readFileSync(path.join(root,x),'utf8');
const inicio=get('index.html'),dashboard=get('dashboard.html');
const home=get('cipa-home.js'),cipa=get('cipa-cadastro.js'),cad=get('cadastro.html');
const tcoGeral=get('tco.html');
assert.doesNotThrow(()=>new Function(home));
const scriptInicio=inicio.indexOf('<script>\nconst db=');
assert.ok(scriptInicio>0);
assert.doesNotThrow(()=>new Function(inicio.slice(scriptInicio+9,inicio.lastIndexOf('</script>'))));
assert.match(inicio,/cipa-home\.js\?v=/);
assert.match(inicio,/modoCipa=!modoCpc&&siglaAtiva==="CIPA"/);
assert.match(inicio,/if\(modoCipa\)CipaHome\.preparar\(\)/);
assert.match(inicio,/CipaHome\.renderizar\(d,dAnt/);
assert.match(home,/Total de ocorrências/);
assert.match(home,/Animais envolvidos/);
assert.match(home,/Área embargada \(ha\)/);
assert.match(home,/Multas aplicadas \(R\$\)/);
assert.match(home,/cipa_fauna/);
assert.match(home,/cipa_termos_embargo/);
assert.match(home,/cipa_autos_infracao/);
assert.doesNotMatch(home,/cipa_tcos_ambientais/);

assert.match(cipa,/<select id="cipaTemTco"/);
assert.match(cipa,/id="cipaNumeroTco"/);
assert.match(cipa,/cadastrar_tco_publico/);
assert.match(cipa,/buscar_bo_para_tco/);
assert.match(cipa,/existentes\.some\(t=>chave\(t\.numero_tco\)===chave\(numero\)\)/);
assert.match(cipa,/preencherTcoDoPpe\(texto\)/);
assert.match(cad,/CipaCadastro\.validarTco\(\)/);
assert.match(cad,/O PPE foi salvo, mas não foi possível concluir/);
assert.match(tcoGeral,/cadastrar_tco_publico/);
assert.doesNotMatch(cipa,/cipa_tcos_ambientais/);

// Testa o leitor do número do TCO sem acesso ao DOM.
const start=cipa.indexOf('  function numeroTcoDoPpe(texto){');
const end=cipa.indexOf('  function preencherTcoDoPpe(texto){',start);
assert.ok(start>=0&&end>start);
const extrair=new Function(cipa.slice(start,end)+'return numeroTcoDoPpe;')();
assert.equal(extrair('TCO Nº 00000096/2026\nBoletim de Ocorrência Nº 00048606/2026'),'00000096/2026');
assert.equal(extrair('TERMO CIRCUNSTANCIADO DE OCORRÊNCIA Nº 96/2026'),'96/2026');
assert.equal(extrair('BO Nº 00048606/2026; Auto de Infração Nº 2026454185'),'');
assert.equal(extrair('Foi lavrado TCO pelo policial, mas sem número informado.'),'');

assert.match(dashboard,/id="cipaTipoInfracao"/);
assert.match(dashboard,/id="cipaSancao"/);
assert.match(dashboard,/id="cipaAnimal"/);
assert.match(dashboard,/id="cipaProcedimento"/);
assert.match(dashboard,/id="cipaDestinacao"/);
assert.match(dashboard,/id="cipaEmbargo"/);
assert.match(dashboard,/id="cipaTco"/);
assert.match(dashboard,/cipa_termos_embargo/);
assert.match(dashboard,/\$\('cipaEmbargosTotal'\)\.textContent=embargos\.length/);
assert.match(dashboard,/const area=somaCampo\(embargos,'area_embargada_ha'\)/);
assert.match(dashboard,/cipaOcorrenciaPassaFiltros/);
assert.match(dashboard,/idsAtual=new Set\(a\.map/);
assert.match(dashboard,/cipaTemFiltroPpe/);
assert.match(dashboard,/if\(filtrarPorPpe&&!ids\.has/);
assert.match(dashboard,/cipaOcorrenciaPassaFiltros\(\{id:x\.ocorrencia_id\},base\)/);
assert.match(dashboard,/cipaAreaDesmatada/);
assert.match(dashboard,/area_desmatada_constatada_ha/);
assert.match(dashboard,/tabCipaAutosDetalhe/);
assert.match(dashboard,/tabCipaEmbargosDetalhe/);
assert.match(cipa,/area_desmatada_constatada_ha/);
assert.match(cipa,/O PPE já possui TCO vinculado/);
const relatorio=get('relatorio-cipa.js');
assert.match(relatorio,/consultaPeriodo\('cipa_termos_embargo'/);
assert.match(relatorio,/soma\(embargos,'area_embargada_ha'\)/);
assert.match(relatorio,/DESMATAMENTO CONSTATADO/);
const migrations=fs.readdirSync(path.join(root,'supabase','migrations'));
assert.ok(migrations.some(x=>x.endsWith('_cipa_area_desmatada_constatada_separada.sql')));
console.log('PASS: quatro KPIs CIPA, filtros cruzados, embargos por termo e TCO no módulo geral.');
