const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');

const cadastro=read('cadastro.html');
const cipaCadastro=read('cipa-cadastro.js');
const cipaExtrator=read('cipa-extrator.js');
const cadastroBase=read('cadastro-base.html');
const dashboard=read('dashboard.html');
const mapaCriminal=read('mapa-criminal.html');
const relatorio=read('relatorio.html');
const relCipa=read('relatorio-cipa.js');

assert.match(cadastro,/const ehCipaCadastro=siglaCadastro==='CIPA'/);
assert.match(cadastro,/ehGiroCadastro\|\|ehCipaCadastro/);
assert.match(cadastro,/CipaCadastro\?\.salvar/);
assert.match(cadastro,/cipa-cadastro\.js/);

assert.match(cipaCadastro,/await window\.SistemaAuth\.ready/);
assert.match(cipaCadastro,/form#formOcorrencia > section/);
assert.match(cipaCadastro,/Dados ambientais — CIPA/);
assert.match(cipaCadastro,/Autos de Infração Ambiental/);
assert.match(cipaCadastro,/Termos de Embargo \/ Interdição/);
assert.match(cipaCadastro,/Fauna \/ TR/);
assert.match(cipaCadastro,/Educação Ambiental/);
assert.match(cipaCadastro,/cipa_autos_infracao/);
assert.match(cipaCadastro,/cipa_termos_embargo/);
assert.match(cipaCadastro,/cipa_autos_notificacao/);
assert.match(cipaCadastro,/cipa_fauna/);
assert.doesNotMatch(cipaCadastro,/id="cipaDataRegistroInicio"/);
assert.doesNotMatch(cipaCadastro,/id="cipaDataRegistroFim"/);
assert.match(cipaExtrator,/AUTO DE INFRA/);
assert.match(cipaExtrator,/TERMO DE EMBARGO/);
assert.match(cipaCadastro,/CipaExtrator\?\.extrair/);
assert.match(cadastro,/cipa-extrator\.js/);
assert.match(cadastroBase,/sie:pdf-texto-extraido/);
assert.match(cipaCadastro,/addEventListener\('sie:pdf-texto-extraido'/);
assert.doesNotMatch(cipaCadastro,/window\.lerTextoPdfLocal/);

assert.match(cadastro,/Local da ocorrência — CIPA/);
assert.match(cadastro,/cipaLocalCoordenadas/);
assert.match(cadastro,/cipaTemCoordenadas/);
assert.match(cadastro,/Informe se o local da ocorrência é URBANO ou RURAL/);
assert.match(cadastro,/north:5\.3,south:-1\.7,east:-58\.8,west:-64\.9/);
assert.match(cadastro,/Digite rua, avenida ou localidade em Roraima/);
assert.match(cadastroBase,/dados\.municipio\|\|"Boa Vista"/);
assert.match(cadastroBase,/municipioAtual/);
assert.match(cadastroBase,/tesseract\.js@7\.0\.0/);
assert.match(cadastroBase,/async function lerCoordenadasCipaPorOcr/);
assert.match(cadastroBase,/pagina\.render\(\{canvasContext:contexto,viewport\}\)/);
assert.match(cadastroBase,/worker\.recognize\(canvas\)/);
assert.match(cadastroBase,/origem:"ocr"/);
assert.match(cadastroBase,/Coordenada não encontrada no texto\. Verificando imagens do PPE/);
assert.match(cadastroBase,/Coordenadas CIPA:/);
assert.match(cipaCadastro,/LOCALIZA\[ÇC\]\[ÃA\]O/);
assert.match(cipaCadastro,/par geográfico válido/);
assert.match(cipaCadastro,/coordenadasDoTexto/);
assert.match(cipaCadastro,/function parseCoordenadas/);
assert.match(cipaCadastro,/function sincronizarCoordenadasLocal/);
assert.match(cipaCadastro,/parseCoordenadas,coordenadasDoTexto,sincronizarCoordenadasLocal/);
assert.match(cadastroBase,/Coordenadas do PPE identificadas/);
assert.match(cipaCadastro,/latitude'\)\.value=p\.lat\.toFixed/);
assert.match(cipaCadastro,/longitude'\)\.value=p\.lon\.toFixed/);
assert.doesNotMatch(cipaCadastro,/id="cipaCoordenadas"/);
assert.match(mapaCriminal,/la>=-2&&la<=6&&lo>=-66&&lo<=-58/);
assert.match(mapaCriminal,/cipa_coordenadas_texto/);
assert.match(mapaCriminal,/function localOcorrencia/);

assert.match(dashboard,/Dashboard Ambiental — CIPA/);
assert.match(dashboard,/Fiscalização e Produtividade Ambiental/);
assert.match(dashboard,/cipa_autos_infracao/);
assert.match(dashboard,/cipa_area_tipo/);
assert.match(dashboard,/cipa_origem_atuacao/);

assert.match(relatorio,/ehCipaRel/);
assert.match(relatorio,/buildRelatorioCipa/);
assert.match(relCipa,/FISCALIZAÇÃO AMBIENTAL/);
assert.match(relCipa,/VALOR DAS MULTAS/);
assert.match(relCipa,/ÁREA EMBARGADA/);
assert.match(relCipa,/FAUNA, EDUCAÇÃO AMBIENTAL E TCO/);

console.log('PASS: módulo ambiental especializado da CIPA validado.');
