const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const ler=f=>fs.readFileSync(path.join(root,f),'utf8');
const home=ler('index.html'),dashboard=ler('dashboard.html'),registro=ler('cipg-produtividade.html');
const homeModulo=ler('cipg-home.js');
const caderno=ler('cipg-caderno.js');
const migracoes=fs.readdirSync(path.join(root,'supabase','migrations'));
const sqlFile=migracoes.find(x=>x.endsWith('_cipg_produtividade_servicos_guarda.sql'));
assert.ok(sqlFile,'Migração CIPG não localizada');
const sql=ler('supabase/migrations/'+sqlFile);
assert.match(sql,/create table if not exists public\.cipg_servicos_guarda/);
assert.match(sql,/PRODUTIVIDADE_CIPG/);
assert.match(sql,/unidades_modulos/);
assert.match(sql,/row level security/);
assert.match(sql,/private\.pode_acessar_unidade/);
assert.match(sql,/private\.pode_escrever_operacional/);
assert.match(sql,/sigla='CIPG'/);
assert.match(sql,/revoke all on public\.cipg_servicos_guarda from anon/);
assert.match(sql,/rondas_realizadas/);
assert.match(sql,/intercorrencias/);
assert.match(sql,/instituicao/);
assert.match(sql,/EDIFICIO_PUBLICO/);
assert.match(sql,/ESTABELECIMENTO_PENAL/);
assert.match(home,/modoCipg/);
assert.match(home,/CipgHome\.preparar/);
assert.match(home,/CipgHome\.consultar/);
assert.match(home,/CipgHome\.renderizar/);
assert.match(home,/cipg-home\.js\?v=/);
assert.doesNotThrow(()=>new Function(homeModulo));
assert.match(homeModulo,/Relatórios de serviço/);
assert.match(homeModulo,/Entradas de PM no hospital/);
assert.match(homeModulo,/Serviços sem alteração/);
assert.match(homeModulo,/Efetivo empregado/);
assert.match(homeModulo,/cipg_servicos_guarda/);

assert.match(dashboard,/id="navCipg"/);
assert.match(dashboard,/id="secCipgProdutividade"/);
assert.match(dashboard,/configurarModuloCipg\(\)/);
assert.match(dashboard,/Dashboard Completo — CIPG/);
assert.match(dashboard,/function renderCipg/);
assert.match(dashboard,/cipgFiltroTipo/);
assert.match(dashboard,/cipgFiltroModalidade/);
assert.match(dashboard,/cipgFiltroInstituicao/);
assert.match(dashboard,/chartCipgCausas/);
assert.match(dashboard,/chartCipgDesfechos/);
assert.match(dashboard,/chartCipgEvolucao/);
assert.match(dashboard,/tabCipgInstituicoes/);
assert.match(dashboard,/consultarCipaPaginado\('cipg_servicos_guarda'/);
const dashScript=dashboard.slice(dashboard.lastIndexOf('<script>')+8,dashboard.lastIndexOf('</script>'));
assert.doesNotThrow(()=>new Function(dashScript));
const homeScript=home.slice(home.lastIndexOf('<script>\nconst db=')+8,home.lastIndexOf('</script>'));
assert.doesNotThrow(()=>new Function(homeScript));
assert.match(registro,/Registrar serviço de guarda/);
assert.match(registro,/cipg-caderno\.js/);
assert.doesNotThrow(()=>new Function(caderno));
assert.match(caderno,/cipg_servicos_guarda/);
assert.match(caderno,/PRODUTIVIDADE_CIPG/);
assert.match(caderno,/data_servico/);
assert.match(caderno,/intercorrencias/);
assert.match(caderno,/efetivo_ordinario/);
assert.match(caderno,/numero_sei/);
assert.doesNotMatch(registro,/policial_nome|escala_futura|posicao_tatica/);
const script=registro.slice(registro.lastIndexOf('<script>')+8,registro.lastIndexOf('</script>'));
assert.doesNotThrow(()=>new Function(script));
console.log('PASS: CIPG ativa, registro seguro de serviços e painéis com filtros e indicadores específicos');
