const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const raiz=path.resolve(__dirname,'..');
const ler=p=>fs.readFileSync(path.join(raiz,p),'utf8');
const pagina=ler('autos-infracao.html');
const dash=ler('dashboard.html');
const cfg=ler('auth-config.js');
const index=ler('index.html');
const mig=ler(path.join('supabase','migrations','20260929195925_fase3q_autos_infracao_ciptur.sql'));
const migAgentes=ler(path.join('supabase','migrations','20261001125309_fase3t_agentes_autuadores_ciptur.sql'));
const migAgentesDados=ler(path.join('supabase','migrations','20261001125343_fase3t_b_importar_agentes_transito_pmrr.sql'));

assert.match(cfg,/"autos-infracao\.html":"cadastro"/);
assert.match(cfg,/"autos-infracao\.html":"AUTOS_INFRACAO"/);
assert.match(index,/href="autos-infracao\.html"[\s\S]*data-module="AUTOS_INFRACAO"/);
assert.match(pagina,/id="dataInfracao"/);
assert.match(pagina,/id="codigo"/);
assert.match(pagina,/id="agenteAutuador"/);
assert.match(pagina,/id="sugestoesAgentes"/);
assert.match(pagina,/buscar_agentes_transito/);
assert.match(pagina,/agente_autuador_id:agenteSelecionado\.id/);
assert.match(pagina,/agente_codigo_snapshot/);
assert.match(pagina,/agente_nome_snapshot/);
assert.match(pagina,/id="houveRemocao"/);
assert.match(pagina,/id="tipoVeiculo"/);
assert.match(pagina,/value="CARRO"/);
assert.match(pagina,/value="MOTO"/);
assert.doesNotMatch(pagina,/id="bairro"/);
assert.doesNotMatch(pagina,/id="logradouro"/);
assert.doesNotMatch(pagina,/id="hora"/);
assert.match(pagina,/codigo_normalizado/);
assert.match(pagina,/c\.descricao/);
assert.match(pagina,/c\.base_legal/);
assert.match(pagina,/c\.valor/);
assert.match(dash,/from\('ciptur_autos_infracao'\)/);
assert.match(dash,/tabCipturInfracoes/);
assert.match(dash,/cipturRemocoesTotal/);
assert.match(dash,/tipo_veiculo_removido/);
assert.doesNotMatch(dash,/tabCipturBairros/);
assert.doesNotMatch(dash,/tabCipturTurnos/);
assert.match(mig,/create table if not exists public\.ciptur_catalogo_infracoes/);
assert.match(mig,/create table if not exists public\.ciptur_autos_infracao/);
assert.match(mig,/'65\.992'/);
assert.match(mig,/Conduzir o veículo registrado sem licenciamento/);
assert.match(mig,/'51\.691'/);
assert.match(mig,/Dirigir sob a influência de álcool/);
assert.match(mig,/AUTOS_INFRACAO/);
assert.match(migAgentes,/create table if not exists public\.ciptur_agentes_transito/);
assert.match(migAgentes,/codigo_ambiguo boolean not null default false/);
assert.match(migAgentes,/buscar_agentes_transito/);
assert.match(migAgentes,/agente_autuador_id uuid references public\.ciptur_agentes_transito/);
assert.match(migAgentes,/Informe o agente autuador do A\.I\./);
assert.match(migAgentesDados,/PM5994/);
assert.match(migAgentesDados,/ADRIEL SOUZA SANTANA/);
assert.match(migAgentesDados,/PM5548/);
const migRemocao=ler(path.join('supabase','migrations','20260929201210_fase3r_remocao_veiculo_ai_ciptur.sql'));
assert.match(migRemocao,/houve_remocao boolean not null default false/);
assert.match(migRemocao,/tipo_veiculo_removido text/);
assert.match(migRemocao,/tipo_veiculo_removido in \('CARRO','MOTO'\)/);

console.log('Módulo de A.I. da CIPTUR validado.');
