begin;

set local lock_timeout = '10s';
set local statement_timeout = '2min';

lock table public.unidades in share row exclusive mode;
lock table public.ocorrencias in share row exclusive mode;
lock table public.google_sheets_sync_outbox in share row exclusive mode;

do $$
declare
  v_unidades_ativas bigint;
begin
  if to_regclass('public.unidades_integracoes') is not null then
    raise exception 'Fase 3D-D cancelada: public.unidades_integracoes já existe.';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema='public'
      and table_name='google_sheets_sync_outbox'
      and column_name='unidade_id'
  ) then
    raise exception 'Fase 3D-D cancelada: google_sheets_sync_outbox.unidade_id já existe.';
  end if;

  if not exists (
    select 1 from public.unidades
    where id='f09a10df-cd1d-48d1-a093-bf731906e175'::uuid
      and sigla='2BPM'
      and ativo=true
  ) then
    raise exception 'Fase 3D-D cancelada: 2BPM oficial ativo não encontrado.';
  end if;

  select count(*) into v_unidades_ativas
  from public.unidades
  where ativo=true;

  if v_unidades_ativas <> 1 then
    raise exception 'Fase 3D-D cancelada: esperada somente uma unidade ativa, encontradas %.', v_unidades_ativas;
  end if;

  if exists (
    select 1
    from public.ocorrencias
    where unidade_id is distinct from 'f09a10df-cd1d-48d1-a093-bf731906e175'::uuid
  ) then
    raise exception 'Fase 3D-D cancelada: existem ocorrências fora do 2BPM.';
  end if;

  if exists (
    select 1
    from public.google_sheets_sync_outbox
    where payload ? 'unidade_id'
      and nullif(payload->>'unidade_id','') is not null
      and payload->>'unidade_id' <> 'f09a10df-cd1d-48d1-a093-bf731906e175'
  ) then
    raise exception 'Fase 3D-D cancelada: existe evento histórico da outbox com unidade diferente do 2BPM.';
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgrelid='public.ocorrencias'::regclass
      and tgname='trg_enqueue_occurrence_for_google_sheets'
      and tgenabled='O'
  ) or not exists (
    select 1 from pg_trigger
    where tgrelid='public.ocorrencias'::regclass
      and tgname='trg_enqueue_deleted_occurrence_for_google_sheets'
      and tgenabled='O'
  ) then
    raise exception 'Fase 3D-D cancelada: triggers atuais do Google Sheets não estão habilitados.';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='public.ocorrencias'::regclass
      and conname='ocorrencias_unidade_fase2_2bpm_chk'
      and convalidated=true
  ) then
    raise exception 'Fase 3D-D cancelada: CHECK temporário do 2BPM não está validado.';
  end if;
end
$$;

create table public.unidades_integracoes (
  id bigint generated by default as identity primary key,
  unidade_id uuid not null,
  tipo text not null,
  google_sheet_id text,
  aba_principal text not null default 'Ocorrências',
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint unidades_integracoes_unidade_fkey
    foreign key (unidade_id) references public.unidades(id)
    on update restrict on delete restrict,
  constraint unidades_integracoes_tipo_chk
    check (tipo = upper(tipo) and btrim(tipo) <> ''),
  constraint unidades_integracoes_sheet_chk
    check (
      tipo <> 'GOOGLE_SHEETS_OCORRENCIAS'
      or (google_sheet_id is not null and btrim(google_sheet_id) <> '')
    ),
  constraint unidades_integracoes_unidade_tipo_uq
    unique (unidade_id, tipo)
);

create index unidades_integracoes_tipo_ativo_idx
  on public.unidades_integracoes (tipo, ativo, unidade_id);

alter table public.unidades_integracoes enable row level security;

revoke all on table public.unidades_integracoes from public, anon, authenticated;
grant select, insert, update, delete on table public.unidades_integracoes to service_role;
grant usage, select on sequence public.unidades_integracoes_id_seq to service_role;

insert into public.unidades_integracoes
  (unidade_id, tipo, google_sheet_id, aba_principal, ativo)
values
  (
    'f09a10df-cd1d-48d1-a093-bf731906e175'::uuid,
    'GOOGLE_SHEETS_OCORRENCIAS',
    '10BcWmWxzSrFghs_y_1L6QchidNWAwS6eAC9T53J_vs8',
    'Ocorrências',
    true
  );

alter table public.google_sheets_sync_outbox
  add column unidade_id uuid;

update public.google_sheets_sync_outbox
set unidade_id = 'f09a10df-cd1d-48d1-a093-bf731906e175'::uuid
where unidade_id is null;

alter table public.google_sheets_sync_outbox
  alter column unidade_id set not null;

alter table public.google_sheets_sync_outbox
  add constraint google_sheets_sync_outbox_unidade_fkey
  foreign key (unidade_id) references public.unidades(id)
  on update restrict on delete restrict;

create index google_sheets_sync_outbox_unidade_status_idx
  on public.google_sheets_sync_outbox (unidade_id, status, next_attempt_at, id);

create or replace function public.enqueue_occurrence_for_google_sheets()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if current_setting('app.google_sheets_ack', true) = '1' then
    return new;
  end if;

  if tg_op = 'INSERT'
     or public.occurrence_business_payload(new)
        is distinct from public.occurrence_business_payload(old) then
    insert into public.google_sheets_sync_outbox
      (occurrence_sync_id, sync_version, unidade_id, payload)
    values
      (new.sync_id, new.sync_version, new.unidade_id, to_jsonb(new))
    on conflict (occurrence_sync_id, sync_version)
    do update
      set unidade_id = excluded.unidade_id,
          payload = excluded.payload,
          status = 'PENDENTE',
          next_attempt_at = now(),
          last_error = null;
  end if;

  return new;
end
$function$;

revoke all on function public.enqueue_occurrence_for_google_sheets()
  from public, anon, authenticated;
grant execute on function public.enqueue_occurrence_for_google_sheets()
  to service_role;

create or replace function public.enqueue_deleted_occurrence_for_google_sheets()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.google_sheets_sync_outbox
    (occurrence_sync_id, sync_version, unidade_id, payload, status, next_attempt_at, last_error)
  values
    (
      old.sync_id,
      old.sync_version + 1,
      old.unidade_id,
      to_jsonb(old) || jsonb_build_object('_deleted', true),
      'PENDENTE',
      now(),
      null
    )
  on conflict (occurrence_sync_id, sync_version)
  do update
    set unidade_id = excluded.unidade_id,
        payload = excluded.payload,
        status = 'PENDENTE',
        next_attempt_at = now(),
        last_error = null;

  return old;
end
$function$;

revoke all on function public.enqueue_deleted_occurrence_for_google_sheets()
  from public, anon, authenticated;
grant execute on function public.enqueue_deleted_occurrence_for_google_sheets()
  to service_role;

create function public.claim_google_sheets_sync_batch_v2(
  batch_size integer default 50,
  p_google_sheet_id text default null
)
returns table(
  event_id bigint,
  occurrence_sync_id uuid,
  sync_version bigint,
  unidade_id uuid,
  unidade_sigla text,
  google_sheet_id text,
  aba_principal text,
  payload jsonb,
  attempts integer
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  return query
  with chosen as (
    select q.id
    from public.google_sheets_sync_outbox q
    join public.unidades_integracoes i
      on i.unidade_id = q.unidade_id
     and i.tipo = 'GOOGLE_SHEETS_OCORRENCIAS'
     and i.ativo = true
    where q.status in ('PENDENTE', 'ERRO')
      and q.next_attempt_at <= now()
      and (p_google_sheet_id is null or i.google_sheet_id = p_google_sheet_id)
    order by q.id
    limit greatest(1, least(batch_size, 200))
    for update of q skip locked
  ),
  changed as (
    update public.google_sheets_sync_outbox q
       set attempts = q.attempts + 1,
           status = 'PENDENTE',
           next_attempt_at = now() + interval '5 minutes'
      from chosen c
     where q.id = c.id
    returning q.id, q.occurrence_sync_id, q.sync_version, q.unidade_id, q.payload, q.attempts
  )
  select
    c.id,
    c.occurrence_sync_id,
    c.sync_version,
    c.unidade_id,
    u.sigla,
    i.google_sheet_id,
    i.aba_principal,
    c.payload,
    c.attempts
  from changed c
  join public.unidades u
    on u.id = c.unidade_id
  join public.unidades_integracoes i
    on i.unidade_id = c.unidade_id
   and i.tipo = 'GOOGLE_SHEETS_OCORRENCIAS'
   and i.ativo = true
  where p_google_sheet_id is null or i.google_sheet_id = p_google_sheet_id
  order by c.id;
end
$function$;

revoke all on function public.claim_google_sheets_sync_batch_v2(integer, text)
  from public, anon, authenticated;
grant execute on function public.claim_google_sheets_sync_batch_v2(integer, text)
  to service_role;

create function public.obter_planilha_usuario()
returns table(
  unidade_id uuid,
  unidade_sigla text,
  google_sheet_id text,
  aba_principal text,
  google_sheet_url text
)
language sql
stable
security definer
set search_path = ''
as $function$
  select
    u.id,
    u.sigla,
    i.google_sheet_id,
    i.aba_principal,
    'https://docs.google.com/spreadsheets/d/' || i.google_sheet_id || '/edit'
  from public.perfis_usuarios p
  join public.unidades u
    on u.id = p.unidade_id
   and u.ativo = true
  join public.unidades_integracoes i
    on i.unidade_id = u.id
   and i.tipo = 'GOOGLE_SHEETS_OCORRENCIAS'
   and i.ativo = true
  where p.user_id = (select auth.uid())
    and p.ativo = true
  limit 1
$function$;

revoke all on function public.obter_planilha_usuario()
  from public, anon, authenticated;
grant execute on function public.obter_planilha_usuario()
  to authenticated, service_role;

do $$
begin
  if (select count(*) from public.unidades_integracoes) <> 1 then
    raise exception 'Fase 3D-D cancelada: esperado exatamente um vínculo de integração.';
  end if;

  if not exists (
    select 1
    from public.unidades_integracoes
    where unidade_id='f09a10df-cd1d-48d1-a093-bf731906e175'::uuid
      and tipo='GOOGLE_SHEETS_OCORRENCIAS'
      and google_sheet_id='10BcWmWxzSrFghs_y_1L6QchidNWAwS6eAC9T53J_vs8'
      and ativo=true
  ) then
    raise exception 'Fase 3D-D cancelada: integração oficial do 2BPM não foi preservada.';
  end if;

  if exists (
    select 1 from public.google_sheets_sync_outbox
    where unidade_id is null
  ) then
    raise exception 'Fase 3D-D cancelada: permaneceram eventos sem unidade.';
  end if;

  if exists (
    select 1 from public.google_sheets_sync_outbox
    where unidade_id <> 'f09a10df-cd1d-48d1-a093-bf731906e175'::uuid
  ) then
    raise exception 'Fase 3D-D cancelada: histórico da outbox foi associado a outra unidade.';
  end if;

  if (select count(*) from public.unidades where ativo=true) <> 1 then
    raise exception 'Fase 3D-D cancelada: outra unidade foi ativada.';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='public.ocorrencias'::regclass
      and conname='ocorrencias_unidade_fase2_2bpm_chk'
      and convalidated=true
  ) then
    raise exception 'Fase 3D-D cancelada: CHECK temporário do 2BPM foi afetado.';
  end if;
end
$$;

commit;